// SKUs
export const GET_SKUS_REQUEST = 'GET_SKUS_REQUEST';
export const GET_SKUS_SUCCESS = 'GET_SKUS_SUCCESS';
export const GET_SKUS_FAILURE = 'GET_SKUS_FAILURE';
export const CREATE_NEW_SKU_REQUEST = 'CREATE_NEW_SKU_REQUEST';
export const CREATE_NEW_SKU_SUCCESS = 'CREATE_NEW_SKU_SUCCESS';
export const CREATE_NEW_SKU_FAILURE = 'CREATE_NEW_SKU_FAILURE';
export const UPDATE_SKU_REQUEST = 'UPDATE_SKU_REQUEST';
export const UPDATE_SKU_SUCCESS = 'UPDATE_SKU_SUCCESS';
export const UPDATE_SKU_FAILURE = 'UPDATE_SKU_FAILURE';
export const DELETE_SKU_REQUEST = 'DELETE_SKU_REQUEST';
export const DELETE_SKU_SUCCESS = 'DELETE_SKU_SUCCESS';
export const DELETE_SKU_FAILURE = 'DELETE_SKU_FAILURE';
export const CHOOSE_SKU_SUCCESS = 'CHOOSE_SKU_SUCCESS';

// Accounts
export const GET_ACCOUNTS_REQUEST = 'GET_ACCOUNTS_REQUEST';
export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS';
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE';
export const CREATE_NEW_ACCOUNT_REQUEST = 'CREATE_NEW_ACCOUNT_REQUEST';
export const CREATE_NEW_ACCOUNT_SUCCESS = 'CREATE_NEW_ACCOUNT_SUCCESS';
export const CREATE_NEW_ACCOUNT_FAILURE = 'CREATE_NEW_ACCOUNT_FAILURE';
export const UPDATE_ACCOUNT_REQUEST = 'UPDATE_ACCOUNT_REQUEST';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const UPDATE_ACCOUNT_FAILURE = 'UPDATE_ACCOUNT_FAILURE';
export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const DELETE_ACCOUNT_FAILURE = 'DELETE_ACCOUNT_FAILURE';
export const CHOOSE_ACCOUNT_SUCCESS = 'CHOOSE_ACCOUNT_SUCCESS';
