# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SkuForma' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SkuForma

  target 'SkuForma-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'react-native-config', :path => '../node_modules/react-native-config'

  end

  target 'SkuFormaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SkuForma-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

end
