/**
 * Color Config
 */

const COLORS = {
  DEEP_PURPLE: '#2B0E7C',
  ELECTRIC_PURPLE: '#9527FF',
  PASTEL_PURPLE: '#9fc3ff',
  PASTEL_BLUE: '#9fc3ff',
  ELECTRIC_BLUE: '#1D84FF',
  ELECTRIC_YELLOW: '#ECFF14',
  YELLOW_ORANGE: '#FFD500',
  ORANGE: '#FF9900',
  RED: '#FF4848',
  ELECTRIC_RED: '#FF1F1F',
  CREAM: '#FEFFF3',
  ACCENT_GRAY: '#BBBBBB',
  GRAY: '#2B2B2B',
  DARK_GRAY: '#1B1B1B',
  MIDNIGHT_GRAY: '#0B0B0B',
};

export { COLORS };
